# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fund. Análisis de Datos
author: Moscow Mavericks
logo: logo.png
copyright: "URJC Máster Data Science"
exclude_patterns: ["**.ipynb_checkpoints"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Moscow-Mavericks/Moscow_Mavericks  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: develop  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: false
  use_repository_button: true
